# Generated by Django 5.2.3 on 2025-06-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
